config_site2/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('site2.urls')),
    path('', include('system.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('mdeditor/', include('mdeditor.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

site2/urls.py
from django.urls import path
from . import views


app_name = 'site2'
urlpatterns = [
    path('', views.index, name='index'),
    path('news/list', views.news_list, name='news_list'),
    # 下記日時による絞り込み
    path('archive/<int:year>', views.news_year_list, name='year'),
    path('archive/<int:year>/<int:month>/', views.news_month_list, name='month'),
    # 下記記事詳細
    path('news/<int:pk>', views.news_detail, name='news_detail'),
    # 下記カテゴリによる絞り込みの
    path('category/<int:pk>', views.news_category_list, name='category'),
    path('c1', views.c1, name='c1'),
    path('company', views.company, name='company'),
    path('confirm', views.confirm, name='confirm'),
    path('contact', views.contact, name='contact'),
    path('finish', views.finish, name='finish'),
    path('form', views.form, name='form'),
    path('item', views.item, name='item'),
    path('link', views.link, name='link'),
    path('recruit', views.recruit, name='recruit'),
    # 採用アーカイブ
    path('recruit/long', views.recruit_archive_long, name='recruit_long'),
    path('recruit/short', views.recruit_archive_short, name='recruit_short'),
    path('service', views.service, name='service'),
]

site2/models.py
from django.db import models
from mdeditor.fields import MDTextField
from django.utils import timezone





# 新着情報

class Category(models.Model):
    name = models.CharField(max_length=100,)
    def __str__(self):
        return self.name
    
PUBLIC_CHOICES = [
    ('1', '公開'),
    ('0', '非公開'),
]

class NewsQuerySet(models.QuerySet):
    def published(self):
        return self.filter(data__lte=timezone.now())


class News(models.Model):
    title = models.CharField(max_length=100, verbose_name='タイトル') 
    category = models.ManyToManyField(Category, verbose_name='カテゴリー')
    content = MDTextField(max_length=500, verbose_name='記事内容')
    public_status = models.BooleanField(verbose_name='公開')
    data = models.DateTimeField(auto_now_add=True, verbose_name='投稿日')

    objects = NewsQuerySet.as_manager()

    def __str__(self):
        return self.title


class Recruit(models.Model):
    title = models.CharField('タイトル', max_length=100)
    discription = MDTextField(max_length=500, verbose_name='記事内容')
    public_status = models.BooleanField('チェックで公開',)
    long_short = models.BooleanField('チェックで短期', default=False)
    data = models.DateField("更新日時", auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.title



    

site2/forms.py
from django import forms
from .models import News

class NewsForm(forms.ModelForm):
    class Meta:
      form = News
      fields = ('title', 'category', 'content', 'data') 

site2/views.py
from django.shortcuts import render
from .models import News, Category, Recruit
from system.views import paginator_query
from django.shortcuts import get_object_or_404
from django.views import generic



# TOPページ
def index(request):
    obj = News.objects.all().order_by('-data')[0:10]
    params = {
        'obj': obj,   
        'title': 'ポートフォリオTOP',
    }
    return render(request, 'site2/index.html', params)


   # 新着情報一覧
def news_list(request):
    obj = News.objects.all().order_by('-data')
    news_list = paginator_query(request, obj, 10)

    params = {
        'obj': news_list,
        'paginator_list': news_list,
        'title': '新着情報一覧',
        'daytime': '2019',
    }

    return render(request, 'site2/news_list.html', params)

class ArchiveListMixin:
    model = News
    date_field = 'data'
    allow_empty = True
    make_object_list = True
    template_name = 'site2/archive_category.html'






# 年別アーカイブ
def news_year_list(request, year):
    obj = News.objects.filter(data__year=year).order_by('-data')
    obj_list = paginator_query(request, obj, 6)
    daytime = '{}年の記事'.format(year)

    params = {
        'obj': obj_list.object_list,
        'daytime': daytime,
        'paginator_list' :obj_list
    }
    return render(request, 'site2/archive_category.html', params)


# 月別アーカイブ
def news_month_list(request, year, month):
    obj = News.objects.filter(data__month=month).order_by('-data')
    daytime = '{}年{}月の記事'.format(year, month)
    obj_list = paginator_query(request, obj, 6)
    params = {
        'obj': obj_list.object_list,
        'daytime': daytime,
        'paginator_list': obj_list,
    }

    return render(request, 'site2/archive_category.html', params)


# 新着カテゴリ別ソート機能
def news_category_list(request, pk):
    obj = News.objects.filter(category=pk).order_by('-data')
    category_name = Category.objects.get(id=pk)
    obj_list = paginator_query(request, obj, 6)
    daytime = '【{}】の記事一覧'.format(category_name)
    params = {
        'obj': obj_list.object_list,
        'daytime': daytime,
        'paginator_list': obj_list,
    }
    return render(request, 'site2/archive_category.html', params)


# 新着情報詳細
def news_detail(request, pk):
    obj = News.objects.get(id=pk)
    params = {
        'obj': obj,
        'title': '新着情報詳細',
    }
    return render(request, 'site2/news_detail.html', params)


 


def c1(request):
    return render(request, 'site2/c1.html')

def company(request):
    return render(request, 'site2/company.html')

def confirm(request):
    return render(request, 'site2/confirm.html')

def contact(request):
    return render(request, 'site2/contact.html')

def finish(request):
    return render(request, 'site2/finish.html')

def form(request):
    return render(request, 'site2/form.html')

def item(request):
    return render(request, 'site2/item.html')

def link(request):
    return render(request, 'site2/link.html')


# 採用ページ関数
def recruit(request):
    obj_short = Recruit.objects.filter(long_short=True, public_status=True)[:5]
    obj_long = Recruit.objects.filter(long_short=False, public_status=True)[:5]
    params = {
        'obj_short': obj_short,
        'obj_long': obj_long,
        
    }
    return render(request, 'site2/recruit.html', params)

# 採用ページ長期アーカイブ
def recruit_archive_long(request):
    obj_recruit = Recruit.objects.filter(long_short=False)

    params = {
        'title': '長期',
        'obj_recruit': obj_recruit,
    }

    return render(request, 'site2/archive_recruit.html', params)

# 採用ページ短期アーカイブ
def recruit_archive_short(request):
    obj_recruit = Recruit.objects.filter(long_short=True)

    params = {
        'title': '短期',
        'obj_recruit': obj_recruit,
    }

    return render(request, 'site2/archive_recruit.html', params)


def service(request):
    return render(request, 'site2/service.html')

site2/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>{{ title }}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="ここにサイト説明を入れます">
<meta name="keywords" content="キーワード１,キーワード２,キーワード３,キーワード４,キーワード５">
<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
<link rel="stylesheet" href="{% static 'css/slide.css' %}" type="text/css">
<script type="text/javascript" src="{% static 'js/openclose.js' %}"></script>
<script type="text/javascript" src="{% static 'js/fixmenu_pagetop.js' %}"></script>
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>

<body id="top">

<header>
<div class="inner">
<h1 id="logo"><a href="{% url 'site2:index' %}"><img src="{% static 'images/logo.png' %}" alt="SAMPLE COMPANY"></a></h1>
<div id="contact">
<p class="tel">TEL:00-0000-0000<span>受付：00:00〜00:00　定休日：水曜日</span></p>
</div>
</div>
</header>

<!--PC用（801px以上端末）メニュー-->
<nav id="menubar">
<ul class="inner">
<li class="current"><a href="{% url 'site2:index' %}">ホーム<span>HOME</span></a></li>
<li><a href="{% url 'site2:company' %}">会社概要<span>COMPANY</span></a></li>
<li><a href="{% url 'site2:service' %}">製品紹介<span>SERVICE</span></a></li>
<li><a href="{% url 'site2:recruit' %}">採用情報<span>RECRUIT</span></a></li>
<li><a href="{% url 'site2:link' %}">リンク<span>LINK</span></a></li>
<li><a href="{% url 'site2:contact' %}">お問い合わせ<span>CONTACT</span></a></li>
</ul>
</nav>
<!--小さな端末用（800px以下端末）メニュー-->
<nav id="menubar-s">
<ul>
<li><a href="{% url 'site2:index' %}">ホーム<span>HOME</span></a></li>
<li><a href="{% url 'site2:company' %}">会社概要<span>COMPANY</span></a></li>
<li><a href="{% url 'site2:service' %}">製品紹介<span>SERVICE</span></a></li>
<li><a href="{% url 'site2:recruit' %}">採用情報<span>RECRUIT</span></a></li>
<li><a href="{% url 'site2:link' %}">リンク<span>LINK</span></a></li>
<li><a href="{% url 'site2:contact' %}">お問い合わせ<span>CONTACT</span></a></li>
</ul>
</nav>

{% block body %}
  
{% endblock body %}


  <!--/#sub-->
  
  </div>
  <!--/#contents-->
  
<footer>

  <div id="footermenu" class="inner">
  <ul>
  <li><a href="#">メニューサンプル</a></li>
  <li><a href="#">メニューサンプル</a></li>
  <li><a href="#">メニューサンプル</a></li>
  <li><a href="#">メニューサンプル</a></li>
  <li><a href="#">メニューサンプル</a></li>
  <li><a href="#">メニューサンプル</a></li>
  </ul>
  <ul>
  <li><a href="#">メニューサンプル</a></li>
  <li><a href="#">メニューサンプル</a></li>
  <li><a href="#">メニューサンプル</a></li>
  <li><a href="#">メニューサンプル</a></li>
  <li><a href="#">メニューサンプル</a></li>
  <li><a href="#">メニューサンプル</a></li>
  </ul>
  <ul>
  <li><a href="#">メニューサンプル</a></li>
  <li><a href="#">メニューサンプル</a></li>
  <li><a href="#">メニューサンプル</a></li>
  <li><a href="#">メニューサンプル</a></li>
  <li><a href="#">メニューサンプル</a></li>
  <li><a href="#">メニューサンプル</a></li>
  </ul>
  <ul>
  <li><a href="#">メニューサンプル</a></li>
  <li><a href="#">メニューサンプル</a></li>
  <li><a href="#">メニューサンプル</a></li>
  <li><a href="#">メニューサンプル</a></li>
  <li><a href="#">メニューサンプル</a></li>
  <li><a href="#">メニューサンプル</a></li>
  </ul>
  <ul>
  <li><a href="#">メニューサンプル</a></li>
  <li><a href="#">メニューサンプル</a></li>
  <li><a href="#">メニューサンプル</a></li>
  <li><a href="#">メニューサンプル</a></li>
  <li><a href="#">メニューサンプル</a></li>
  <li><a href="#">メニューサンプル</a></li>
  </ul>
  </div>
  <!--/footermenu-->
  
  <div id="copyright">
  <small>Copyright&copy; <a href="{% url 'site2:index' %}">SAMPLE COMPANY</a> All Rights Reserved.</small>
  <span class="pr"><a href="http://template-party.com/" target="_blank">《Web Design:Template-Party》</a></span>
  </div>
  
  </footer>
  
  <p class="nav-fix-pos-pagetop"><a href="#">↑</a></p>
  
  <!--メニュー開閉ボタン-->
  <div id="menubar_hdr" class="close"></div>
  <!--メニューの開閉処理条件設定　800px以下-->
  <script type="text/javascript">
  if (OCwindowWidth() <= 800) {
    open_close("menubar_hdr", "menubar-s");
  }
  </script>
  
  </body>
  </html>
  