config_site2/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('site2.urls')),
    path('', include('system.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('mdeditor/', include('mdeditor.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

site2/urls.py
from django.urls import path
from . import views


app_name = 'site2'
urlpatterns = [
    path('', views.index, name='index'),
    path('news/list', views.news_list, name='news_list'),
    # 下記日時による絞り込み
    path('archive/<int:year>', views.news_year_list, name='year'),
    path('archive/<int:year>/<int:month>/', views.news_month_list, name='month'),
    # 下記記事詳細
    path('news/<int:pk>', views.news_detail, name='news_detail'),
    # 下記カテゴリによる絞り込みの
    path('category/<int:pk>', views.news_category_list, name='category'),
    path('c1', views.c1, name='c1'),
    path('company', views.company, name='company'),
    path('confirm', views.confirm, name='confirm'),
    path('contact', views.contact, name='contact'),
    path('finish', views.finish, name='finish'),
    path('form', views.form, name='form'),
    path('item', views.item, name='item'),
    path('link', views.link, name='link'),
    path('recruit', views.recruit, name='recruit'),
    # 採用アーカイブ
    path('recruit/long', views.recruit_archive_long, name='recruit_long'),
    path('recruit/short', views.recruit_archive_short, name='recruit_short'),
    path('service', views.service, name='service'),
]

system/urls.py
from django.urls import path
from . import views

app_name = 'system'

urlpatterns = [
    path('system/login/', views.Login.as_view(), name='login'),
    path('system/logout/', views.Logout.as_view(), name='logout'),
    path('system/index/', views.index, name='index'),
    # 以下新着情報
    path('system/news/', views.news, name='news'),
    path('system/news/<int:pk>/', views.news_edit, name='news_edit'),
    path('system/news/news_add', views.news_add, name='news_add'),
    path('system/news/<int:pk>', views.news_delete, name='news_delete'),
    # 以下採用ページ
    path('system/recruit/', views.recruit, name='recruit'),
    path('system/recruit/add/', views.recruit_add, name='recruit_add'),
    path('system/recruit/<int:pk>', views.recruit_edit, name='recruit_edit'),
    path('system/recruit/del/<int:pk>', views.recruit_delete, name='recruit_delete'),
]

system/models.py
from django.db import models

system/forms.py
from django.contrib.auth.forms import AuthenticationForm
from site2.models import News
from django import forms
from django_summernote.widgets import SummernoteWidget
from site2.models import Category, PUBLIC_CHOICES, News, Recruit
from site2 import models



class LoginForm(AuthenticationForm):
    def __init__(self, request,  *args, **kwargs):
        super().__init__(request, *args, **kwargs)

        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'  
            field.widget.attrs['placeholder'] = field.label


class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        fields = ('title', 'category', 'content', 'public_status',)
        widgets = {
            'category' :forms.CheckboxSelectMultiple,
            
        }

PUBLIC_CHOICES = PUBLIC_CHOICES + [('', '選択してください')]
class NewsSearchForm(forms.Form):
    title = forms.CharField(max_length='100', required=False)
    category = forms.ModelChoiceField(models.Category.objects, label='カテゴリー', required=True)
    public = forms.ChoiceField(label='公開/非公開', choices=PUBLIC_CHOICES, required=False)


class RecruitForm(forms.ModelForm):
    class Meta:
        model = Recruit
        fields = ('title', 'discription', 'public_status', 'long_short')




    

system/views.py
from django.shortcuts import render, get_object_or_404, redirect

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (LoginView, LogoutView)
from .forms import LoginForm, NewsForm, RecruitForm
from django.contrib.auth.decorators import login_required
from site2.models import News, Category, Recruit
from django.contrib import messages
from django.db.models import Q
# from . forms import NewsSearchFormSet
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

class Login(LoginView):
    form_class = LoginForm
    template_name = 'system/login.html'


class Logout(LoginRequiredMixin, LogoutView):
    template_name = 'system/login.html'


@login_required
def index(request):
    return render(request, 'system/index.html')



# ページネーションの関数
def paginator_query(request, queryset, count):
    paginator = Paginator(queryset, count)
    page = request.GET.get('page')
    try:
        news_list = paginator.page(page)
    except PageNotAnInteger:
        news_list = paginator.page(1)
    except EmptyPage:
        news_list = paginator.page(paginator.num_pages)
    return news_list

# 新着情報の一覧
@login_required
def news(request):
    news = News.objects.all().order_by('-data')
     # 検索機能の処理関数
    q_title = request.GET.get('get_title')
    if q_title:
        news = News.objects.filter(Q(title__icontains=q_title))

    news_list = paginator_query(request, news, 6)
    params = {  
        'news': news_list.object_list,
        'paginator_list': news_list,
    }
    return render(request, 'system/news.html', params)




# 新着情報の新規作成
@login_required
def news_add(request):
    if request.method == 'POST':
        obj = News()
        form = NewsForm(request.POST, instance=obj)
        if form.is_valid():
            form.save()
            return redirect('system:news')
    else:
        form = NewsForm()
    return render(request, 'system/news_add.html', {'form': form})

# 新着情報の編集
@login_required
def news_edit(request, pk):
    obj = News.objects.get(id=pk)
    if (request.method == 'POST'):
        form = NewsForm(request.POST, instance=obj)
        if form.is_valid():
            form.save()
            return redirect(to='/system/news')
    params = {
        'form': NewsForm(instance=obj),
        'id': pk,
    }
    return render(request, 'system/news_edit.html', params)




# 新着情報の削除
@login_required
def news_delete(request, pk):
    obj = News.objects.get(id=pk)
    if (request.method == 'POST'):
        obj.delete()
        return redirect(to='/system/news')
    params = {
        'obj': obj,
        'id': pk,
    }
    
    return render(request, 'system/news_delete.html', params)



# 採用ページ一覧
@login_required
def recruit(request):
    obj = Recruit.objects.all()
    # 検索機能の関数
    q_title = request.GET.get('get_title')
    if q_title:
        obj = Recruit.objects.filter(Q(title__icontains=q_title))
    
    recruit_list = paginator_query(request, obj, 3)
    params = {
        'obj': recruit_list.object_list,
        'paginator_list' :recruit_list,
    }

    return render(request, 'system/recruit.html', params)

# 採用ページ新規作成
@login_required
def recruit_add(request):
    if request.method == 'POST':
        obj = Recruit()
        form = RecruitForm(request.POST, instance=obj)
        if form.is_valid:
            form.save()
            return redirect('system:recruit')
    else:
        form = RecruitForm()
    return render(request, 'system/recruit_add.html',{'form': form})


# 採用ページ編集
@login_required
def recruit_edit(request, pk):
    obj = Recruit.objects.get(id=pk)
    if (request.method == 'POST'):
        form = RecruitForm(request.POST, instance=obj)
        if form.is_valid():
            form.save()
            return redirect(to='/system/recruit')
    
    params = {
        'form': RecruitForm(instance=obj),
        'id': pk,
    }

    return render(request, 'system/recruit_edit.html', params)

# 採用ページの削除
@login_required
def recruit_delete(request, pk):
    obj = Recruit.objects.get(id=pk,)
    if request.method == 'POST':
        obj.delete()
        return redirect(to='/system/recruit')
    
    params = {
        'obj': obj,
        'id': pk,
    }
    return render(request, 'system/recruit_delete.html', params)

system/templates/system/login.html
{% load static %}
<!doctype html>
<html lang="ja" class="fullscreen-bg">

<head>
	<title>Login</title>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
	<!-- VENDOR CSS -->
	<link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/vendor/font-awesome/css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/vendor/linearicons/style.css' %}">
	<!-- MAIN CSS -->
	<link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
	<!-- FOR DEMO PURPOSES ONLY. You should remove this in your project -->
	<link rel="stylesheet" href="{% static 'assets/css/demo.css' %}">
	<!-- GOOGLE FONTS -->
	<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">
	<!-- ICONS -->
	<link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/apple-icon.png' %}">
	<link rel="icon" type="image/png" sizes="96x96" href="{% static 'assets/img/favicon.png' %}">
</head>

<body>
	<!-- WRAPPER -->
	<div id="wrapper">
		<div class="vertical-align-wrap">
			<div class="vertical-align-middle">
				<div class="auth-box ">
					<div class="left">
						<div class="content">
							<div class="header">
								<!-- <div class="logo text-center"><img src="assets/img/logo-dark.png" alt="Klorofil Logo"></div> -->
								<p class="lead">Login to your account</p>
							</div>
							<!-- 以下フォーム -->
							<form class="form-auth-small" action="" method="POST">
								{% csrf_token %}
								{% for field in form %}
								<div class="form-group">  
									<!-- <label for="signin-email" class="control-label sr-only">Email</label> -->
									<!-- <input type="email" class="form-control" id="signin-email" value="samuel.gold@domain.com" placeholder="Email"> -->
									{{ field }}
								</div>
								{% endfor %}
								{% for error in form.non_field_errors %}
								 <p>{{ error }}</p>
								 {% endfor %}
								<!-- <div class="form-group">
									 <label for="signin-password" class="control-label sr-only">Password</label> 
									 <input type="password" class="form-control" id="signin-password" value="thisisthepassword" placeholder="Password"> 
								</div> -->
								
								<div class="form-group clearfix">
									<label class="fancy-checkbox element-left">
										<input type="checkbox">
										<span>Remember me</span>
									</label>
								</div>
								<button type="submit" class="btn btn-primary btn-lg btn-block">LOGIN</button>
								<div class="bottom">
									<span class="helper-text"><i class="fa fa-lock"></i> <a href="#">Forgot password?</a></span>
								</div>
							</form>

						</div>
					</div>
					<div class="right">
						<div class="overlay"></div>
						<div class="content text">
							<h1 class="heading">CMS管理画面です</h1>
							<p>by The Develovers</p>
						</div>
					</div>
					<div class="clearfix"></div>
				</div>
			</div>
		</div>
	</div>
	<!-- END WRAPPER -->
</body>

</html>

system/templates/system/news.html
{% extends 'base_system.html' %}
{% load static %}

		{% block body %}
		<!-- MAIN -->
		<div class="main">
			<!-- MAIN CONTENT -->
			<div class="main-content">
				<div class="container-fluid">

					<!-- TABLE STRIPED -->
					<form method="get" action="">
						<input name='get_title' placeholder="タイトルを検索" value="{{ request.GET.get_title }}" type="text">
							<button class="btn btn-primary" type="submit">検索</button>
					</form>
					<div class="panel">

						<div class="panel-heading" align="center">
							<h3 class="panel-title">記事一覧</h3>
						</div>
						<button style="margin-left:30px" type="button" onclick="location.href='{% url 'system:news_add' %}'" class="btn btn-primary">新規作成</button>
						<div class="panel-body">
							<table class="table table-striped">
								<thead>
									<tr>
										<th>タイトル</th>
										<th>カテゴリー</th>
										<th>記事内容</th>
										<th>削除・編集</th>
										<th>公開/非公開</th>
										<th>更新日</th>
									</tr>
								</thead>
								<tbody>
									{% for news in paginator_list %}
									<tr>
										<td>{{ news.title }}</td>
										<td>{% for ctg in news.category.all %}{{ ctg }}{% endfor %}</td>
										<td>{{ news.content|truncatechars:10|safe }}</td>
										<td>
											<button type="button" onclick="location.href='{% url 'system:news_edit' news.id %}'" class="btn btn-success">編集</button>
											<button type="button" onclick="location.href='{% url 'system:news_delete' news.id %}'" class="btn btn-danger">削除</button>
										</td>
										{% if news.public_status %}
										<td>公開</td>
										{% else %}
										<td>非公開</td>
										{% endif %}
										<td>{{ news.data }}</td>
									</tr>
									{% endfor %}
								</tbody>
							</table>
								{% include 'includes/paginator.html' %}

						</div>
					</div>
					
					<!-- END TABLE STRIPED -->
		
{% endblock body %}

system/templates/system/news_add.html
{% extends 'base_system.html' %}
{% load static %}

		{% block body %}
		<!-- MAIN -->
		<div class="main">
			<!-- MAIN CONTENT -->
			<div class="main-content">
				<div class="container-fluid">
					<!-- OVERVIEW -->
					<div class="panel panel-headline">
						<div class="panel-heading">
							<body>
									<form action="{% url 'system:news_add' %}" method="POST">
									{% csrf_token %}
									<div class="panel-body">
										<table class="table table-bordered">
											<tbody>
												{{ form.media }}
												{{ form.as_table }}
											</tbody>
										</table>
										<p><input type="submit" value="投稿" class="btn btn-primary"></p>
									</div>
									</form>
							</body>
						</div>
					</div>
			
	</div>
{% endblock body %}

system/templates/system/news_delete.html
{% extends 'base_system.html' %}
{% load static %}

		{% block body %}
		<!-- MAIN -->
		<div class="main">
			<!-- MAIN CONTENT -->
			<div class="main-content">
				<div class="container-fluid">
					
          <!-- TABLE STRIPED -->
          <div class="panel">
            <div class="panel-heading" align="center">
              <h3 class="panel-title">以下の記事を削除します</h3>
            </div>
            <div class="panel-body">
              <table class="table table-striped">
                <tr><th>ID</th><td>{{ obj.id }}</td></tr>
                <tr><th>タイトル</th><td>{{ obj.title }}</td></tr>
                <tr><th>カテゴリー</th><td>{{ obj.category }}</td></tr>
                <tr><th>記事内容</th><td>{{ obj.content }}</td></tr>
              </table>
              <form action="{% url 'system:news_delete' id %}" method="post">
              {% csrf_token %}
                <button style="margin-left:30px" type="submit"  class="btn btn-danger">削除</button>
              </form>
            </div>
            
          </div>
          
          <!-- END TABLE STRIPED -->
		
	</div>
{% endblock body %}

system/templates/system/news_edit.html
{% extends 'base_system.html' %}
{% load static %}

		{% block body %}
		<!-- MAIN -->
		<div class="main">
			<!-- MAIN CONTENT -->
			<div class="main-content">
				<div class="container-fluid">
					<!-- OVERVIEW -->
					<div class="panel panel-headline">
						<div class="panel-heading">
							<body>
									<form action="{% url 'system:news_edit' id %}" method="POST">
									{% csrf_token %}
									<div class="panel-body">
										<table class="table table-bordered">
											<tbody>
												{{ form.media }}
												{{ form.as_table }}
											</tbody>
										</table>
										<p><input type="submit" value="投稿" class="btn btn-primary"></p>
									</div>
									</form>
							</body>
						</div>
					</div>
			
	</div>
{% endblock body %}

system/templates/system/recruit.html
{% extends 'base_system.html' %}
{% load static %}

{% block body %}
<!-- MAIN -->
<div class="main">
    <!-- MAIN CONTENT -->
    <div class="main-content">
        <div class="container-fluid">

            <!-- TABLE STRIPED -->
            <form method="get" action="">
                <input name='get_title' placeholder="タイトルを検索" value="{{ request.GET.get_title }}" type="text">
                    <button class="btn btn-primary" type="submit">検索</button>
            </form>
            <div class="panel">

                <div class="panel-heading" align="center">
                    <h3 class="panel-title">採用情報一覧</h3>
                </div>
                <button style="margin-left:30px" type="button" onclick="location.href='{% url 'system:recruit_add' %}'" class="btn btn-primary">新規作成</button>
                <div class="panel-body">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>タイトル</th>
                                <th>記事内容</th>
                                <th>公開設定</th>
                                <th>長期/短期</th>
                                <th>編集/削除</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for recruit in paginator_list %}
                            <tr>
                                <td>{{ recruit.id }}</td>
                                <td>{{ recruit.title }}</td>
                                <td>{{ recruit.discription|truncatechars:10 }}</td>
                                {% if recruit.public_status %}
                                    <td>公開</td>
                                {% else %}
                                    <td>非公開</td>
                                {% endif %}
                                {% if recruit.long_short %}
                                    <td>短期募集</td>
                                {% else %}
                                    <td>長期募集</td>
                                {% endif %}
                                <td>
                                    <button type="submit" onclick="location.href='{% url 'system:recruit_edit' recruit.id %}'" class="btn btn-success">編集</button>
                                    <button type="submit" onclick="location.href='{% url 'system:recruit_delete' recruit.id %}'" class="btn btn-danger">削除</button>
								</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                        {% include 'includes/paginator.html' %}

                </div>
            </div>
            <!-- END TABLE STRIPED -->
{% endblock body %}

system/templates/system/recruit_add.html
{% extends 'base_system.html' %}
{% load static %}

		{% block body %}
		<!-- MAIN -->
		<div class="main">
			<!-- MAIN CONTENT -->
			<div class="main-content">
				<div class="container-fluid">
					<!-- OVERVIEW -->
					<div class="panel panel-headline">
						<div class="panel-heading">
							<body>
									<form action="{% url 'system:recruit_add' %}" method="POST">
									{% csrf_token %}
									<div class="panel-body">
										<table class="table table-bordered">
											<tbody>
												{{ form.media }}
												{{ form.as_table }}
											</tbody>
										</table>
										<p><input type="submit" value="投稿" class="btn btn-primary"></p>
									</div>
									</form>
							</body>
						</div>
					</div>
			
	</div>
{% endblock body %}

system/templates/system/recruit_delete.html
{% extends 'base_system.html' %}
{% load static %}

		{% block body %}
		<!-- MAIN -->
		<div class="main">
			<!-- MAIN CONTENT -->
			<div class="main-content">
				<div class="container-fluid">
					
          <!-- TABLE STRIPED -->
          <div class="panel">
            <div class="panel-heading" align="center">
              <h3 class="panel-title">以下の記事を削除します</h3>
            </div>
            <div class="panel-body">
              <table class="table table-striped">
                <tr><th>ID</th><td>{{ obj.id }}</td></tr>
                <tr><th>タイトル</th><td>{{ obj.title }}</td></tr>
                <tr><th>記事内容</th><td>{{ obj.discription }}</td></tr>
                {% if obj.public_status %}
                    <tr><th>公開設定</th><td>公開</td></tr>
                {% else %}
                    <tr><th>公開設定</th><td>非公開</td></tr>
                {% endif %}
                {% if obj.long_short %}
                    <tr><th>短期募集・長期募集</th><td>短期募集</td></tr>
                {% else %}
                    <tr><th>短期募集・長期募集</th><td>長期募集</td></tr>
                {% endif %}
              </table>
              <form action="{% url 'system:news_delete' id %}" method="post">
              {% csrf_token %}
                <button style="margin-left:30px" type="submit"  class="btn btn-danger">削除</button>
              </form>
            </div>
            
          </div>
          
          <!-- END TABLE STRIPED -->
		
	</div>
{% endblock body %}

system/templates/system/recruit_edit.html
{% extends 'base_system.html' %}
{% load static %}

		{% block body %}
		<!-- MAIN -->
		<div class="main">
			<!-- MAIN CONTENT -->
			<div class="main-content">
				<div class="container-fluid">
					<!-- OVERVIEW -->
					<div class="panel panel-headline">
						<div class="panel-heading">
							<body>
									<form action="{% url 'system:recruit_edit' id %}" method="POST">
									{% csrf_token %}
									<div class="panel-body">
										<table class="table table-bordered">
											<tbody>
												{{ form.media }}
												{{ form.as_table }}
											</tbody>
										</table>
										<p><input type="submit" value="投稿" class="btn btn-primary"></p>
									</div>
									</form>
							</body>
						</div>
					</div>
			
	</div>
{% endblock body %}