config_site2/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('site2.urls')),
    path('', include('system.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('mdeditor/', include('mdeditor.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

site2/urls.py
from django.urls import path
from . import views


app_name = 'site2'
urlpatterns = [
    path('', views.index, name='index'),
    path('news/list', views.news_list, name='news_list'),
    # 下記日時による絞り込み
    path('archive/<int:year>', views.news_year_list, name='year'),
    path('archive/<int:year>/<int:month>/', views.news_month_list, name='month'),
    # 下記記事詳細
    path('news/<int:pk>', views.news_detail, name='news_detail'),
    # 下記カテゴリによる絞り込みの
    path('category/<int:pk>', views.news_category_list, name='category'),
    path('c1', views.c1, name='c1'),
    path('company', views.company, name='company'),
    path('confirm', views.confirm, name='confirm'),
    path('contact', views.contact, name='contact'),
    path('finish', views.finish, name='finish'),
    path('form', views.form, name='form'),
    path('item', views.item, name='item'),
    path('link', views.link, name='link'),
    path('recruit', views.recruit, name='recruit'),
    # 採用アーカイブ
    path('recruit/long', views.recruit_archive_long, name='recruit_long'),
    path('recruit/short', views.recruit_archive_short, name='recruit_short'),
    path('service', views.service, name='service'),
]

system/urls.py
from django.urls import path
from . import views

app_name = 'system'

urlpatterns = [
    path('system/login/', views.Login.as_view(), name='login'),
    path('system/logout/', views.Logout.as_view(), name='logout'),
    path('system/index/', views.index, name='index'),
    # 以下新着情報
    path('system/news/', views.news, name='news'),
    path('system/news/<int:pk>/', views.news_edit, name='news_edit'),
    path('system/news/news_add', views.news_add, name='news_add'),
    path('system/news/<int:pk>', views.news_delete, name='news_delete'),
    # 以下採用ページ
    path('system/recruit/', views.recruit, name='recruit'),
    path('system/recruit/add/', views.recruit_add, name='recruit_add'),
    path('system/recruit/<int:pk>', views.recruit_edit, name='recruit_edit'),
    path('system/recruit/del/<int:pk>', views.recruit_delete, name='recruit_delete'),
]

system/models.py
from django.db import models

system/forms.py
from django.contrib.auth.forms import AuthenticationForm
from site2.models import News
from django import forms
from django_summernote.widgets import SummernoteWidget
from site2.models import Category, PUBLIC_CHOICES, News, Recruit
from site2 import models



class LoginForm(AuthenticationForm):
    def __init__(self, request,  *args, **kwargs):
        super().__init__(request, *args, **kwargs)

        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'  
            field.widget.attrs['placeholder'] = field.label


class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        fields = ('title', 'category', 'content', 'public_status',)
        widgets = {
            'category' :forms.CheckboxSelectMultiple,
            
        }

PUBLIC_CHOICES = PUBLIC_CHOICES + [('', '選択してください')]
class NewsSearchForm(forms.Form):
    title = forms.CharField(max_length='100', required=False)
    category = forms.ModelChoiceField(models.Category.objects, label='カテゴリー', required=True)
    public = forms.ChoiceField(label='公開/非公開', choices=PUBLIC_CHOICES, required=False)


class RecruitForm(forms.ModelForm):
    class Meta:
        model = Recruit
        fields = ('title', 'discription', 'public_status', 'long_short')




    

system/views.py
from django.shortcuts import render, get_object_or_404, redirect

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (LoginView, LogoutView)
from .forms import LoginForm, NewsForm, RecruitForm
from django.contrib.auth.decorators import login_required
from site2.models import News, Category, Recruit
from django.contrib import messages
from django.db.models import Q
# from . forms import NewsSearchFormSet
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

class Login(LoginView):
    form_class = LoginForm
    template_name = 'system/login.html'


class Logout(LoginRequiredMixin, LogoutView):
    template_name = 'system/login.html'


@login_required
def index(request):
    return render(request, 'system/index.html')



# ページネーションの関数
def paginator_query(request, queryset, count):
    paginator = Paginator(queryset, count)
    page = request.GET.get('page')
    try:
        news_list = paginator.page(page)
    except PageNotAnInteger:
        news_list = paginator.page(1)
    except EmptyPage:
        news_list = paginator.page(paginator.num_pages)
    return news_list

# 新着情報の一覧
@login_required
def news(request):
    news = News.objects.all().order_by('-data')
     # 検索機能の処理関数
    q_title = request.GET.get('get_title')
    if q_title:
        news = News.objects.filter(Q(title__icontains=q_title))

    news_list = paginator_query(request, news, 6)
    params = {  
        'news': news_list.object_list,
        'paginator_list': news_list,
    }
    return render(request, 'system/news.html', params)




# 新着情報の新規作成
@login_required
def news_add(request):
    if request.method == 'POST':
        obj = News()
        form = NewsForm(request.POST, instance=obj)
        if form.is_valid():
            form.save()
            return redirect('system:news')
    else:
        form = NewsForm()
    return render(request, 'system/news_add.html', {'form': form})

# 新着情報の編集
@login_required
def news_edit(request, pk):
    obj = News.objects.get(id=pk)
    if (request.method == 'POST'):
        form = NewsForm(request.POST, instance=obj)
        if form.is_valid():
            form.save()
            return redirect(to='/system/news')
    params = {
        'form': NewsForm(instance=obj),
        'id': pk,
    }
    return render(request, 'system/news_edit.html', params)




# 新着情報の削除
@login_required
def news_delete(request, pk):
    obj = News.objects.get(id=pk)
    if (request.method == 'POST'):
        obj.delete()
        return redirect(to='/system/news')
    params = {
        'obj': obj,
        'id': pk,
    }
    
    return render(request, 'system/news_delete.html', params)



# 採用ページ一覧
@login_required
def recruit(request):
    obj = Recruit.objects.all()
    # 検索機能の関数
    q_title = request.GET.get('get_title')
    if q_title:
        obj = Recruit.objects.filter(Q(title__icontains=q_title))
    
    recruit_list = paginator_query(request, obj, 3)
    params = {
        'obj': recruit_list.object_list,
        'paginator_list' :recruit_list,
    }

    return render(request, 'system/recruit.html', params)

# 採用ページ新規作成
@login_required
def recruit_add(request):
    if request.method == 'POST':
        obj = Recruit()
        form = RecruitForm(request.POST, instance=obj)
        if form.is_valid:
            form.save()
            return redirect('system:recruit')
    else:
        form = RecruitForm()
    return render(request, 'system/recruit_add.html',{'form': form})


# 採用ページ編集
@login_required
def recruit_edit(request, pk):
    obj = Recruit.objects.get(id=pk)
    if (request.method == 'POST'):
        form = RecruitForm(request.POST, instance=obj)
        if form.is_valid():
            form.save()
            return redirect(to='/system/recruit')
    
    params = {
        'form': RecruitForm(instance=obj),
        'id': pk,
    }

    return render(request, 'system/recruit_edit.html', params)

# 採用ページの削除
@login_required
def recruit_delete(request, pk):
    obj = Recruit.objects.get(id=pk,)
    if request.method == 'POST':
        obj.delete()
        return redirect(to='/system/recruit')
    
    params = {
        'obj': obj,
        'id': pk,
    }
    return render(request, 'system/recruit_delete.html', params)

system/templates/base_system.html
{% load static %}
<!doctype html>
<html lang="ja">

<head>
	<title>ダッシュボード</title>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
	<!-- VENDOR CSS -->
	<link rel="stylesheet" href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/vendor/font-awesome/css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/vendor/linearicons/style.css' %}">
	<link rel="stylesheet" href="{% static 'assets/vendor/chartist/css/chartist-custom.css' %}">
	<!-- MAIN CSS -->
	<link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
	<!-- FOR DEMO PURPOSES ONLY. You should remove this in your project -->
	<link rel="stylesheet" href="{% static 'assets/css/demo.css' %}">
	<!-- GOOGLE FONTS -->
	<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">
	<!-- ICONS -->
	<link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/apple-icon.png' %}">
	<link rel="icon" type="image/png" sizes="96x96" href="{% static 'assets/img/favicon.png' %}">
</head>
	<!-- WRAPPER -->
	<div id="wrapper">
		<!-- NAVBAR -->
		<nav class="navbar navbar-default navbar-fixed-top">
			<div class="brand">
				<a href=""><img src="{% static 'assets/img/logo-dark.png' %}" alt="Klorofil Logo" class="{% static 'img-responsive logo' %}"></a>
			</div>
			<div class="container-fluid">
				<div class="navbar-btn">
					<button type="button" class="btn-toggle-fullwidth"><i class="lnr lnr-arrow-left-circle"></i></button>
				</div>
				<!-- <form class="navbar-form navbar-left">
					<div class="input-group">
						<input type="text" value="" class="form-control" placeholder="Search dashboard...">
						<span class="input-group-btn"><button type="button" class="btn btn-primary">Go</button></span>
					</div>
				</form> -->
				 <div class="navbar-btn navbar-btn-right">
					<a class="btn btn-success update-pro" href="{% url 'site2:index' %}" title="Upgrade to Pro" target="_blank"><i class="fa fa-rocket"></i> <span>サイトTOPに戻る</span></a>
				</div> 
				<div id="navbar-menu">
					<ul class="nav navbar-nav navbar-right">
						<!-- <li class="dropdown">
							<a href="#" class="dropdown-toggle icon-menu" data-toggle="dropdown">
								<i class="lnr lnr-alarm"></i>
								<span class="badge bg-danger">5</span>
							</a>
							<ul class="dropdown-menu notifications">
								<li><a href="#" class="notification-item"><span class="dot bg-warning"></span>System space is almost full</a></li>
								<li><a href="#" class="notification-item"><span class="dot bg-danger"></span>You have 9 unfinished tasks</a></li>
								<li><a href="#" class="notification-item"><span class="dot bg-success"></span>Monthly report is available</a></li>
								<li><a href="#" class="notification-item"><span class="dot bg-warning"></span>Weekly meeting in 1 hour</a></li>
								<li><a href="#" class="notification-item"><span class="dot bg-success"></span>Your request has been approved</a></li>
								<li><a href="#" class="more">See all notifications</a></li>
							</ul>
						</li> -->
						<!-- <li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="lnr lnr-question-circle"></i> <span>Help</span> <i class="icon-submenu lnr lnr-chevron-down"></i></a>
							<ul class="dropdown-menu">
								<li><a href="#">Basic Use</a></li>
								<li><a href="#">Working With Data</a></li>
								<li><a href="#">Security</a></li>
								<li><a href="#">Troubleshooting</a></li>
							</ul>
						</li> -->
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="{% static 'assets/img/user.png' %}" class="img-circle" alt="Avatar"> <span>Samuel</span> <i class="icon-submenu lnr lnr-chevron-down"></i></a>
							<ul class="dropdown-menu">
								<li><a href="#"><i class="lnr lnr-user"></i> <span>My Profile</span></a></li>
								<li><a href="#"><i class="lnr lnr-envelope"></i> <span>Message</span></a></li>
								<li><a href="#"><i class="lnr lnr-cog"></i> <span>Settings</span></a></li>
								<li><a href="#"><i class="lnr lnr-exit"></i> <span>Logout</span></a></li>
							</ul>
						</li>
						<!-- <li>
							<a class="update-pro" href="https://www.themeineed.com/downloads/klorofil-pro-bootstrap-admin-dashboard-template/?utm_source=klorofil&utm_medium=template&utm_campaign=KlorofilPro" title="Upgrade to Pro" target="_blank"><i class="fa fa-rocket"></i> <span>UPGRADE TO PRO</span></a>
						</li> -->
					</ul>
				</div>
			</div>
        </nav>
        		<!-- LEFT SIDEBAR -->
		<div id="sidebar-nav" class="sidebar">
			<div class="sidebar-scroll">
				<nav>
					<ul class="nav">
						<li><a href="{% url 'system:index' %}" class="active"><i class="lnr lnr-home"></i> <span>管理画面TOP</span></a></li>
						<li><a href="{% url 'system:news' %}" class=""><i class="lnr lnr-code"></i> <span>新着情報</span></a></li>
						<li><a href="charts.html" class=""><i class="lnr lnr-chart-bars"></i> <span>製品管理</span></a></li>
						<li><a href="{% url 'system:recruit' %}" class=""><i class="lnr lnr-cog"></i> <span>採用管理</span></a></li>
						<li><a href="panels.html" class=""><i class="lnr lnr-cog"></i> <span>お問い合わせ管理</span></a></li>
					</ul>
				</nav>
			</div>
		</div>
        <!-- END LEFT SIDEBAR -->
    {% block body %}

    {% endblock body %}


    <footer>
        <div class="container-fluid">
            <p class="copyright">&copy; 2017 <a href="https://www.themeineed.com" target="_blank">Theme I Need</a>. All Rights Reserved.</p>
        </div>
    </footer>
    <!-- Javascript -->
	<script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
	<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'assets/vendor/jquery-slimscroll/jquery.slimscroll.min.js' %}"></script>
	<script src="{% static 'assets/vendor/jquery.easy-pie-chart/jquery.easypiechart.min.js' %}"></script>
	<script src="{% static 'assets/vendor/chartist/js/chartist.min.js' %}"></script>
	<script src="{% static 'assets/scripts/klorofil-common.js' %}"></script>
	<script>
	$(function() {
		var data, options;

		// headline charts
		data = {
			labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
			series: [
				[23, 29, 24, 40, 25, 24, 35],
				[14, 25, 18, 34, 29, 38, 44],
			]
		};

		options = {
			height: 300,
			showArea: true,
			showLine: false,
			showPoint: false,
			fullWidth: true,
			axisX: {
				showGrid: false
			},
			lineSmooth: false,
		};

		new Chartist.Line('#headline-chart', data, options);


		// visits trend charts
		data = {
			labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
			series: [{
				name: 'series-real',
				data: [200, 380, 350, 320, 410, 450, 570, 400, 555, 620, 750, 900],
			}, {
				name: 'series-projection',
				data: [240, 350, 360, 380, 400, 450, 480, 523, 555, 600, 700, 800],
			}]
		};

		options = {
			fullWidth: true,
			lineSmooth: false,
			height: "270px",
			low: 0,
			high: 'auto',
			series: {
				'series-projection': {
					showArea: true,
					showPoint: false,
					showLine: false
				},
			},
			axisX: {
				showGrid: false,

			},
			axisY: {
				showGrid: false,
				onlyInteger: true,
				offset: 0,
			},
			chartPadding: {
				left: 20,
				right: 20
			}
		};

		new Chartist.Line('#visits-trends-chart', data, options);


		// visits chart
		data = {
			labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
			series: [
				[6384, 6342, 5437, 2764, 3958, 5068, 7654]
			]
		};

		options = {
			height: 300,
			axisX: {
				showGrid: false
			},
		};

		new Chartist.Bar('#visits-chart', data, options);


		// real-time pie chart
		var sysLoad = $('#system-load').easyPieChart({
			size: 130,
			barColor: function(percent) {
				return "rgb(" + Math.round(200 * percent / 100) + ", " + Math.round(200 * (1.1 - percent / 100)) + ", 0)";
			},
			trackColor: 'rgba(245, 245, 245, 0.8)',
			scaleColor: false,
			lineWidth: 5,
			lineCap: "square",
			animate: 800
		});

		var updateInterval = 3000; // in milliseconds

		setInterval(function() {
			var randomVal;
			randomVal = getRandomInt(0, 100);

			sysLoad.data('easyPieChart').update(randomVal);
			sysLoad.find('.percent').text(randomVal);
		}, updateInterval);

		function getRandomInt(min, max) {
			return Math.floor(Math.random() * (max - min + 1)) + min;
		}

	});
	</script>
</body>

</html>